include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_redundant_argument_values: true
    unnecessary_this: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    unnecessary_parenthesis: true
    unnecessary_string_interpolations: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_raw_strings: true
    use_rethrow_when_possible: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    valid_regexps: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    missing_return: error
    invalid_assignment: warning
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true